---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:41:59Z"
  name: carts-canary
  resourceVersion: "932787"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: ed562383-0c53-11ea-ba69-42010a8400a2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
